/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    customers: CustomerAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    colors: Color;
    sizes: Size;
    courses: Course;
    'course-directions': CourseDirection;
    orders: Order;
    carts: Cart;
    customers: Customer;
    'promo-codes': PromoCode;
    broadcasts: Broadcast;
    reviews: Review;
    pages: Page;
    posts: Post;
    subscribers: Subscriber;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    sizes: SizesSelect<false> | SizesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-directions': CourseDirectionsSelect<false> | CourseDirectionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    broadcasts: BroadcastsSelect<false> | BroadcastsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('uk' | 'en') | ('uk' | 'en')[];
  globals: {
    'home-page': HomePage;
    'shop-page': ShopPage;
    'courses-page': CoursesPage;
    about: About;
    settings: Setting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'shop-page': ShopPageSelect<false> | ShopPageSelect<true>;
    'courses-page': CoursesPageSelect<false> | CoursesPageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'uk' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Customer | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Готові прикраси, набори для створення та матеріали.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Один-два рядки під назвою на сторінці товару.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Перше фото — головне. Друге показується при наведенні на картку.
   */
  images?: (number | Media)[] | null;
  /**
   * Базова ціна. Для окремих варіацій її можна перевизначити нижче.
   */
  price: number;
  /**
   * Заповніть, якщо хочете показати перекреслену ціну.
   */
  oldPrice?: number | null;
  generateColors?: (number | Color)[] | null;
  generateSizes?: (number | Size)[] | null;
  generateStock?: number | null;
  /**
   * Наявні комбінації лишаться недоторканими.
   */
  generateVariants?: boolean | null;
  variants?:
    | {
        color?: (number | null) | Color;
        size?: (number | null) | Size;
        sku?: string | null;
        /**
         * Порожньо — береться базова.
         */
        price?: number | null;
        stock: number;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Використовується, якщо варіацій немає.
   */
  stock?: number | null;
  isKit?: boolean | null;
  kitItems?: (number | Product)[] | null;
  /**
   * Дрібниці, які покупець зможе додати до набору прямо на сторінці.
   */
  addons?: (number | Product)[] | null;
  category?: (number | null) | Category;
  status?: ('draft' | 'published') | null;
  featured?: boolean | null;
  /**
   * Блок «Може сподобатись» у кошику. Якщо не відмічено жодного товару, показується найдешевший із наявних.
   */
  suggestInCart?: boolean | null;
  /**
   * Заповнюється автоматично з назви. Змінюйте, тільки якщо розумієте наслідки для SEO.
   */
  slug?: string | null;
  priceFrom?: number | null;
  inStock?: boolean | null;
  totalStock?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Що зображено. Потрібно для Google і для людей, які користуються читалками екрана.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  title: string;
  /**
   * Заповнюється автоматично з назви. Змінюйте, тільки якщо розумієте наслідки для SEO.
   */
  slug?: string | null;
  /**
   * Наприклад #C2410C. Показується кружечком у фільтрі й на картці товару.
   */
  hex: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes".
 */
export interface Size {
  id: number;
  title: string;
  /**
   * Заповнюється автоматично з назви. Змінюйте, тільки якщо розумієте наслідки для SEO.
   */
  slug?: string | null;
  /**
   * Менше число — вище у списку.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Заповнюється автоматично з назви. Змінюйте, тільки якщо розумієте наслідки для SEO.
   */
  slug?: string | null;
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Курс — це набір майстер-класів. Окремий МК теж заводиться тут, просто з одним уроком.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  tagline?: string | null;
  cover?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price: number;
  oldPrice?: number | null;
  level?: ('beginner' | 'medium' | 'advanced') | null;
  lessons?:
    | {
        title: string;
        description?: string | null;
        /**
         * Показується покупцю тільки після оплати. Публічно не видно.
         */
        canvaUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  accessType: 'telegram' | 'canva' | 'both';
  /**
   * Наприклад -1001234567890. Бот має бути адміністратором каналу з правом створювати запрошення.
   */
  telegramChatId?: string | null;
  canvaUrl?: string | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  direction: number | CourseDirection;
  status?: ('draft' | 'published') | null;
  featured?: boolean | null;
  /**
   * Заповнюється автоматично з назви. Змінюйте, тільки якщо розумієте наслідки для SEO.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-directions".
 */
export interface CourseDirection {
  id: number;
  title: string;
  /**
   * Заповнюється автоматично з назви. Змінюйте, тільки якщо розумієте наслідки для SEO.
   */
  slug?: string | null;
  tagline?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  paymentStatus?: ('pending' | 'paid' | 'partial' | 'cancelled' | 'refunded') | null;
  items?:
    | {
        kind: 'product' | 'course';
        title: string;
        quantity: number;
        price: number;
        product?: (number | null) | Product;
        course?: (number | null) | Course;
        variantId?: string | null;
        variantLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  customer?: (number | null) | Customer;
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  deliveryMethod?: ('np_branch' | 'np_locker' | 'np_courier' | 'ukrposhta') | null;
  deliveryCity?: string | null;
  deliveryBranch?: string | null;
  /**
   * Тільки для Укрпошти.
   */
  deliveryPostcode?: string | null;
  comment?: string | null;
  subtotal: number;
  discount?: number | null;
  deliveryCost?: number | null;
  total: number;
  promoCode?: (number | null) | PromoCode;
  /**
   * Для накладеного платежу — сплачена наперед частина.
   */
  prepaidAmount?: number | null;
  paymentMethod?: ('card' | 'cod') | null;
  paymentReference?: string | null;
  /**
   * ID чека в Checkbox. Порожньо — ПРРО ще не підключено.
   */
  fiscalReceipt?: string | null;
  fulfillmentStatus?: ('new' | 'packing' | 'shipped' | 'done' | 'cancelled') | null;
  trackingNumber?: string | null;
  /**
   * Галочка з форми оформлення.
   */
  newsletter?: boolean | null;
  accessGranted?: boolean | null;
  metaFbp?: string | null;
  metaFbc?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  phone?: string | null;
  savedCourses?: (number | Course)[] | null;
  savedProducts?: (number | Product)[] | null;
  /**
   * Заповнюється автоматично після оплати. Доступ безтерміновий.
   */
  access?:
    | {
        course?: (number | null) | Course;
        relatedOrder?: (number | null) | Order;
        grantedAt?: string | null;
        telegramInviteLink?: string | null;
        id?: string | null;
      }[]
    | null;
  deliveryMethod?: ('np_branch' | 'np_locker' | 'np_courier' | 'ukrposhta') | null;
  deliveryCity?: string | null;
  deliveryBranch?: string | null;
  paymentMethod?: ('card' | 'cod') | null;
  receiptChannel?: ('email' | 'sms') | null;
  /**
   * Останні цифри картки, якою платили. Приходить від WayForPay — ми номера не бачимо й не зберігаємо.
   */
  cardMask?: string | null;
  subscribedToNewsletter?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: number;
  /**
   * Регістр не має значення — код завжди зберігається великими літерами.
   */
  code: string;
  type: 'percent' | 'fixed';
  value: number;
  appliesTo?: ('all' | 'courses' | 'products') | null;
  validFrom?: string | null;
  validUntil?: string | null;
  /**
   * Порожньо — без обмежень.
   */
  usageLimit?: number | null;
  minOrderTotal?: number | null;
  usedCount?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Незавершені кошики. Звідси беруться листи про кинутий кошик.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  token: string;
  customer?: (number | null) | Customer;
  /**
   * Для листа про кинутий кошик.
   */
  email?: string | null;
  items?:
    | {
        kind: 'product' | 'course';
        itemId: string;
        variantId?: string | null;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  reminderSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Напишіть лист, поставте галочку «Надіслати» і збережіть.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcasts".
 */
export interface Broadcast {
  id: number;
  subject: string;
  /**
   * Звичайний текст без розмітки — так лист не потрапляє в спам.
   */
  body: string;
  audience?: ('subscribers' | 'customers' | 'all') | null;
  alsoTelegram?: boolean | null;
  /**
   * Знімається автоматично після відправлення.
   */
  send?: boolean | null;
  sentAt?: string | null;
  sentCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Нові відгуки не показуються на сайті, доки ви їх не схвалите.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  authorName: string;
  city?: string | null;
  rating: number;
  text: string;
  photos?: (number | Media)[] | null;
  product?: (number | null) | Product;
  course?: (number | null) | Course;
  status?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Тексти сторінок «Про бренд», «Доставка й оплата», «Оферта».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Заповнюється автоматично з назви. Змінюйте, тільки якщо розумієте наслідки для SEO.
   */
  slug?: string | null;
  intro?: string | null;
  cover?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Порожньо — береться назва сторінки.
   */
  metaTitle?: string | null;
  /**
   * До 160 символів. Це те, що людина бачить у пошуку під заголовком.
   */
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Заповнюється автоматично з назви. Змінюйте, тільки якщо розумієте наслідки для SEO.
   */
  slug?: string | null;
  excerpt?: string | null;
  cover?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Наприклад: вʼязання, догляд, подарунки.
   */
  tags?: string[] | null;
  relatedProducts?: (number | Product)[] | null;
  relatedCourses?: (number | Course)[] | null;
  /**
   * Порожньо — береться назва сторінки.
   */
  metaTitle?: string | null;
  /**
   * До 160 символів. Це те, що людина бачить у пошуку під заголовком.
   */
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  source?: ('footer' | 'checkout' | 'manual') | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'sizes';
        value: number | Size;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-directions';
        value: number | CourseDirection;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: number | PromoCode;
      } | null)
    | ({
        relationTo: 'broadcasts';
        value: number | Broadcast;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  images?: T;
  price?: T;
  oldPrice?: T;
  generateColors?: T;
  generateSizes?: T;
  generateStock?: T;
  generateVariants?: T;
  variants?:
    | T
    | {
        color?: T;
        size?: T;
        sku?: T;
        price?: T;
        stock?: T;
        image?: T;
        id?: T;
      };
  stock?: T;
  isKit?: T;
  kitItems?: T;
  addons?: T;
  category?: T;
  status?: T;
  featured?: T;
  suggestInCart?: T;
  slug?: T;
  priceFrom?: T;
  inStock?: T;
  totalStock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes_select".
 */
export interface SizesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  cover?: T;
  gallery?: T;
  description?: T;
  price?: T;
  oldPrice?: T;
  level?: T;
  lessons?:
    | T
    | {
        title?: T;
        description?: T;
        canvaUrl?: T;
        id?: T;
      };
  accessType?: T;
  telegramChatId?: T;
  canvaUrl?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  direction?: T;
  status?: T;
  featured?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-directions_select".
 */
export interface CourseDirectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  paymentStatus?: T;
  items?:
    | T
    | {
        kind?: T;
        title?: T;
        quantity?: T;
        price?: T;
        product?: T;
        course?: T;
        variantId?: T;
        variantLabel?: T;
        id?: T;
      };
  customer?: T;
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  deliveryMethod?: T;
  deliveryCity?: T;
  deliveryBranch?: T;
  deliveryPostcode?: T;
  comment?: T;
  subtotal?: T;
  discount?: T;
  deliveryCost?: T;
  total?: T;
  promoCode?: T;
  prepaidAmount?: T;
  paymentMethod?: T;
  paymentReference?: T;
  fiscalReceipt?: T;
  fulfillmentStatus?: T;
  trackingNumber?: T;
  newsletter?: T;
  accessGranted?: T;
  metaFbp?: T;
  metaFbc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  token?: T;
  customer?: T;
  email?: T;
  items?:
    | T
    | {
        kind?: T;
        itemId?: T;
        variantId?: T;
        quantity?: T;
        id?: T;
      };
  reminderSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  savedCourses?: T;
  savedProducts?: T;
  access?:
    | T
    | {
        course?: T;
        relatedOrder?: T;
        grantedAt?: T;
        telegramInviteLink?: T;
        id?: T;
      };
  deliveryMethod?: T;
  deliveryCity?: T;
  deliveryBranch?: T;
  paymentMethod?: T;
  receiptChannel?: T;
  cardMask?: T;
  subscribedToNewsletter?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  appliesTo?: T;
  validFrom?: T;
  validUntil?: T;
  usageLimit?: T;
  minOrderTotal?: T;
  usedCount?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcasts_select".
 */
export interface BroadcastsSelect<T extends boolean = true> {
  subject?: T;
  body?: T;
  audience?: T;
  alsoTelegram?: T;
  send?: T;
  sentAt?: T;
  sentCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  authorName?: T;
  city?: T;
  rating?: T;
  text?: T;
  photos?: T;
  product?: T;
  course?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  cover?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  tags?: T;
  relatedProducts?: T;
  relatedCourses?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Розвилка на вході: дві гілки бренду. Заголовка тут немає — посередині стоїть лого.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Ліворуч на комп’ютері, зверху на телефоні. Веде на /courses.
   */
  learn?: {
    label?: string | null;
    /**
     * Вертикальне, від 1200 px по довшій стороні. Порожньо — фото з коду.
     */
    image?: (number | null) | Media;
    /**
     * Читають ті, хто користується екранним диктором, і Google.
     */
    alt?: string | null;
  };
  /**
   * Праворуч на комп’ютері, знизу на телефоні. Веде на /shop.
   */
  shop?: {
    label?: string | null;
    /**
     * Вертикальне, від 1200 px по довшій стороні. Порожньо — фото з коду.
     */
    image?: (number | null) | Media;
    /**
     * Читають ті, хто користується екранним диктором, і Google.
     */
    alt?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Тексти на /shop. Картки товарів і категорій сюди не входять — вони беруться з «Товарів» і «Категорій».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page".
 */
export interface ShopPage {
  id: number;
  hero?: {
    label?: string | null;
    /**
     * Перенесення рядка в цьому полі стає перенесенням на сайті.
     */
    title?: string | null;
    body?: string | null;
    cta?: string | null;
  };
  categories?: {
    label?: string | null;
    title?: string | null;
  };
  /**
   * Блок із трьома кроками: як оформити, як пакуємо, як отримати.
   */
  delivery?: {
    label?: string | null;
    title?: string | null;
    /**
     * У макеті їх три в ряд. Більше — перенесуться на наступний рядок.
     */
    steps?:
      | {
          /**
           * Як у макеті: 01, 02, 03.
           */
          number?: string | null;
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  journal?: {
    label?: string | null;
    title?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Тексти на /courses. Самі курси й напрями редагуються в розділі «Курси».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page".
 */
export interface CoursesPage {
  id: number;
  hero?: {
    label?: string | null;
    /**
     * Перенесення рядка в цьому полі стає перенесенням на сайті.
     */
    title?: string | null;
    body?: string | null;
    cta?: string | null;
  };
  directions?: {
    label?: string | null;
    title?: string | null;
  };
  /**
   * Блок із трьома кроками: як купити, як приходить доступ, як дивитись.
   */
  afterPayment?: {
    label?: string | null;
    title?: string | null;
    /**
     * У макеті їх три в ряд. Більше — перенесуться на наступний рядок.
     */
    steps?:
      | {
          /**
           * Як у макеті: 01, 02, 03.
           */
          number?: string | null;
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Показується капслоком. У макеті — «ПРО БРЕНД».
   */
  label?: string | null;
  title: string;
  /**
   * Основний текст, темний.
   */
  lead?: string | null;
  /**
   * Продовження, приглушеним кольором.
   */
  body?: string | null;
  photo?: (number | null) | Media;
  /**
   * Рівно три: у макеті вони стоять в один ряд по третині ширини.
   */
  values?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Наприклад: «Безкоштовна доставка від 1500 ₴». Порожньо — рядок не показується. На головній його немає: там сторінка без шапки.
   */
  announcement?: string | null;
  phone?: string | null;
  /**
   * Публічна — показується в підвалі сайту.
   */
  email?: string | null;
  /**
   * Куди писати про нові замовлення. Порожньо — сповіщення йдуть лише в Telegram. Тут доречна робоча адреса, яку читають щодня.
   */
  orderNotifyEmail?: string | null;
  /**
   * Типово сповіщення приходить лише про оплачені. З галочкою — і про ті, де людина дійшла до оплати й не заплатила: інколи це просто не пройшла картка, і дзвінок повертає покупця. Але таких замовлень завжди більше, ніж оплачених.
   */
  notifyPendingOrders?: boolean | null;
  instagram?: string | null;
  telegram?: string | null;
  /**
   * Порожньо — доставка завжди платна за тарифами перевізника.
   */
  freeDeliveryFrom?: number | null;
  /**
   * Те, що видно в пошуку й на вкладці браузера. Порожньо — береться назва з коду.
   */
  seoTitle?: string | null;
  /**
   * До 160 символів — далі пошук обрізає.
   */
  seoDescription?: string | null;
  /**
   * Показується, коли посилання на сайт кидають у Instagram, Telegram чи Facebook. Найкраще 1200×630.
   */
  seoImage?: (number | null) | Media;
  /**
   * Зніміть галочку, поки сайт наповнюється: Google його не покаже. Не забудьте повернути на запуску.
   */
  searchVisible?: boolean | null;
  /**
   * search.google.com/search-console → Додати ресурс → HTML-тег. Потрібен лише вміст content="…".
   */
  googleVerification?: string | null;
  /**
   * Ідентифікатор виду G-XXXXXXX.
   */
  gaId?: string | null;
  /**
   * Число з 15–16 цифр із Events Manager.
   */
  metaPixelId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  learn?:
    | T
    | {
        label?: T;
        image?: T;
        alt?: T;
      };
  shop?:
    | T
    | {
        label?: T;
        image?: T;
        alt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page_select".
 */
export interface ShopPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        title?: T;
        body?: T;
        cta?: T;
      };
  categories?:
    | T
    | {
        label?: T;
        title?: T;
      };
  delivery?:
    | T
    | {
        label?: T;
        title?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  journal?:
    | T
    | {
        label?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page_select".
 */
export interface CoursesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        title?: T;
        body?: T;
        cta?: T;
      };
  directions?:
    | T
    | {
        label?: T;
        title?: T;
      };
  afterPayment?:
    | T
    | {
        label?: T;
        title?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  lead?: T;
  body?: T;
  photo?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  announcement?: T;
  phone?: T;
  email?: T;
  orderNotifyEmail?: T;
  notifyPendingOrders?: T;
  instagram?: T;
  telegram?: T;
  freeDeliveryFrom?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  searchVisible?: T;
  googleVerification?: T;
  gaId?: T;
  metaPixelId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}